# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProjectAnimation2' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'MSSlidingPanelController'
  pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
  # Pods for ProjectAnimation2

end
