# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Exe_CoreData' do
pod 'MGSwipeTableCell'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Exe_CoreData

end
